kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: csi-cryptpvc-attacher
spec:
  serviceName: "csi-cryptpvc-attacher"
  replicas: 1
  selector:
    matchLabels:
      app: csi-cryptpvc-attacher
  template:
    metadata:
      labels:
        app: csi-cryptpvc-attacher
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - cryptpvc-csi
            topologyKey: kubernetes.io/hostname
      serviceAccountName: csi-attacher
      containers:
        - name: csi-attacher
          image: quay.io/k8scsi/csi-attacher:v3.0.0-rc1
          args:
            - --v=5
            - --csi-address=/csi/csi.sock
          securityContext:
            # This is necessary only for systems with SELinux, where
            # non-privileged sidecar containers cannot access unix domain socket
            # created by privileged CSI driver container.
            privileged: true
          volumeMounts:
          - mountPath: /csi
            name: socket-dir

      volumes:
        - hostPath:
            path: /var/lib/kubelet/plugins/csi-cryptpvc
            type: DirectoryOrCreate
          name: socket-dir
