name: ci

on:
  # workflow_run:
  #   workflows: ["previous"]
  #   branches: [master]
  #   types: [completed]
  push:
    branches: [ master ]
    paths:
      - .github/workflows/ci.yml
      - hack/test-csi-sanity.sh
      - hack/test-e2e-run.sh
      - cmd/**
      - pkg/**
      - test/**
  pull_request:
    branches: [ master ]
    paths:
      - .github/workflows/ci.yml
      - hack/test-csi-sanity.sh
      - hack/test-e2e-run.sh
      - cmd/**
      - pkg/**
      - test/**

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout git repository"
      uses: actions/checkout@v2

    - name: "Build cryptpvc-csi (go build) + csi-sanity"
      run: docker build -t cryptpvc-test-sanity -f dockerfiles/cryptpvc.dockerfile --target test-sanity .

    - name: "Test cryptpvc-csi using csi-sanity"
      run: docker run --privileged --rm -it cryptpvc-test-sanity

    - name: "Pre-release runtime image for e2e testing"
      run: |
        docker build -t ghcr.io/danielsel/cryptpvc-csi:testing -f dockerfiles/cryptpvc.dockerfile .
        echo $PAT | docker login ghcr.io --username danielsel --password-stdin
        docker push ghcr.io/danielsel/cryptpvc-csi:testing

  test-e2e-kind:
    needs: build-image
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout git repository"
      uses: actions/checkout@v2

    - name: "Setup Go (golang) environment"
      uses: actions/setup-go@v2
      with:
        go-version: '^1.4'

    - name: "Install kubetest"
      run: "go get -u k8s.io/test-infra/kubetest"

    - name: "Setup KinD cluster for e2e testing"
      uses: engineerd/setup-kind@v0.4.0
      with:
        name: cryptpvc-e2e
        config: test/testdata/e2e-kind-cluster.yml

    - name: "Deploy cryptpvc-csi:testing to KinD cluster"
      run: hack/deploy.sh
      env:
        CRYPTPVC_CSI_TAG: testing

    - name: "Run E2E storage tests using kubetest"
      run: 'kubetest --deployment=local --test --check-version-skew=false --test_args="--ginkgo.focus=External.*Storage.* --storage.testdriver=/test/testdata/k8s-e2e-test-driver.yaml" --extract v1.18.6'